### ISSUE TITLE
Something causing "Finishing Boot" hangs on CarbonROM. - Issue by, and resolved by Carbon

### ISSUE THREAD

**Issue by joelmaxuel** [CM-zenfone2/android_device_asus_mofd-common#5]
Midnight last night I ran a build for CarbonROM, and this morning I tested it.  It was...interesting.  From a clean flash (even system wiped), and dalvik wiped after install (before first boot), the splashscreen started, boot animation, okay things are going good so far, and then, straight to "Updating media contacts", "Starting Apps", and finally "Finishing Boot" where it hang (with a thick red border flashing a few times in the final message).

I rebooted, and got the dreadful "Unfortunately, System UI has stopped" FC on loop.  Magic keys to get into Fastboot wouldn't work, my saving grace is that insecure adb was enabled in the kernel (thanks for that) so I could reboot into recovery.

I clean flashed again, this time I took a logcat, and this is the beginning.

http://pastebin.com/YSQKrxC8

Note later on, I would get the messages:

> I/dex2oat (  784): /system/bin/dex2oat --zip-fd=6 --zip-location=/system/framework/com.google.android.camera2.jar --oat-fd=7 --oat-location=/data/dalvik-cache/x86/system@framework@com.google.android.camera2.jar@classes.dex--instruction-set=x86 --instruction-set-features=default --runtime-arg -Xms64m --runtime-arg -Xmx512m --compiler-filter=interpret-only --swap-fd=8
> I/dex2oat (  784): Decided to run without swap.

...over and over again.  So I reverted this commit:
https://github.com/CM-zenfone2/android_kernel_asus_moorefield/commit/9de3be10cdd9989496a151df391000d29f05dbc3

For good measure, this one too:
https://github.com/CM-zenfone2/android_kernel_asus_moorefield/commit/79d972aed78172b934f248a3ef1076b23a03edfc

Built, tested, and at least I got the optimizations this time.  But I am still stuck on "Finishing Boot" (no red border this time).  (Interestingly enough, adb was down this time, but the fastboot hotkeys thankfully worked.)  Is there something in the logcat that points out a clue (I can PM the full version)?  I am building a newer upstream now just in case it was something on Carbon's end (they didn't notice anything).

Thanks for all you do.  I should really put together some donation monies.

**Comment by crpalmer** [comment]
First, you must be running a -eng build.  That's what the flashing red
borders are (I believe that means that an app is taking too long in its
main thread to respond to events).  You get tons of that when running a
-eng build.  The -eng build is also what gave you the insecure boot.img.

To get to fastboot, try unplugging the phone and then long pressing power
to shut it down and then long press power + volume (up or down, I forget
which).  Either the sequence doesn't work at all with the phone plugged in
or at least not reliability for me.

I have no idea what your actual problem is though.  You'd need to post a
longer logcat and a dmesg too.

**Comment by joelmaxuel** [comment]
Hmm, I may have made that mistake in the lunch process for the first build.  Since the second one did not have that problem (or the insecure boot feature), I would have gotten it right.

But because insecure boot wasn't in the second build I wasn't able to provide an updated logcat (device list was always empty).

It's Power+Volume-Up, which I did (unplugged, with intentions of holding Volume-Up until in fastboot), several times - it would vibrate but nothing would come up for the first build only.  But then again, -eng build.

Trying to remember, what are the options that provide insecure boot?  May put those in place for debugging purposes.  IIRC, to be placed in the mofd.mk file:

> ADDITIONAL_DEFAULT_PROPERTIES += \
>    ro.secure=0 \
>    ro.adb.secure=0 \
>    ro.debuggable=1 \
>    service.adb.root=1 \
>    persist.service.adb.enable=1 \
>    persist.service.debuggable=1

I can provide the full logcat of the first failed build tonight (3.2MB), I will host it on my dropbox.

**Comment by joelmaxuel** [comment]
Since I realize you are probably seeing this via email,  I will add the links here:
https://www.dropbox.com/s/0nia1j7uw0tsybx/carbon.txt?dl=0

Filtered for E/'s and F/'s
https://www.dropbox.com/s/fsecuz6b1f9xaxo/carbon.csv?dl=0

**Comment by joelmaxuel** [comment]
Set 2 (September 1st build, logcat and dmesg):
https://www.dropbox.com/sh/3umbi7ds6mq359e/AACSlKzJIcy_9vTRsf_Sn8F6a?dl=0
Thank you.

**Comment by jrior001** [comment]
You are picking up our entire topic:zenfone2_bringup from CM review correct? Your logcat all is see is it scanning a lot of music tracks, there not real failure I see.

**Comment by joelmaxuel** [comment]
I am, and then some apparently.  Once of the failures pointed out to me was the SIM erroring out on registering.  Then  I realized, I had ril patched to both 12.1 and 12.1-caf branches.  Trying a build with just 12.1 patched.

With scanning music, yes that was all happening in the background.  The "Finishing Boot" message stayed for so long, the screen faded, then went to sleep mode.  So in spite of that hang, backend processes were still functional.

We will see what the night brings...

**Comment by crpalmer** [comment]
Media scanning could be related to:

http://review.cyanogenmod.org/#/c/107979/

although I doubt it as that fixes a deadlock and it sounds like something
is printed repeatedly in the log and therefore unrelated....

**Comment by crpalmer** [comment]
This crash looks like it's probably the problem though:

E/AndroidRuntime( 7624): FATAL EXCEPTION: main
E/AndroidRuntime( 7624): Process: com.android.systemui, PID: 7624
E/AndroidRuntime( 7624): java.lang.NullPointerException: Attempt to
invoke virtual method 'android.view.View
android.widget.FrameLayout.findViewById(int)' on a null object
reference
E/AndroidRuntime( 7624):    at
com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(PhoneStatusBar.java:1129)
E/AndroidRuntime( 7624):    at
com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(PhoneStatusBar.java:3929)
E/AndroidRuntime( 7624):    at
com.android.systemui.statusbar.phone.PhoneStatusBar.createAndAddWindows(PhoneStatusBar.java:3900)
E/AndroidRuntime( 7624):    at
com.android.systemui.statusbar.BaseStatusBar.start(BaseStatusBar.java:652)
E/AndroidRuntime( 7624):    at
com.android.systemui.statusbar.phone.PhoneStatusBar.start(PhoneStatusBar.java:887)
E/AndroidRuntime( 7624):    at
com.android.systemui.statusbar.SystemBars.createStatusBarFromConfig(SystemBars.java:110)
E/AndroidRuntime( 7624):    at
com.android.systemui.statusbar.SystemBars.onNoService(SystemBars.java:62)
E/AndroidRuntime( 7624):    at
com.android.systemui.statusbar.ServiceMonitor.startService(ServiceMonitor.java:228)
E/AndroidRuntime( 7624):    at
com.android.systemui.statusbar.ServiceMonitor.access$000(ServiceMonitor.java:49)
E/AndroidRuntime( 7624):    at
com.android.systemui.statusbar.ServiceMonitor$1.handleMessage(ServiceMonitor.java:73)
E/AndroidRuntime( 7624):    at
android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 7624):    at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 7624):    at
android.app.ActivityThread.main(ActivityThread.java:5293)
E/AndroidRuntime( 7624):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7624):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 7624):    at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime( 7624):    at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
I/ContactsProvider( 7601): Aggregation algorithm upgraded for 0 raw
contacts in 66ms

This sounds like it might be more of a carbon issue.

**Comment by joelmaxuel** [comment]
Was a Carbon problem, and this commit fixed it:
http://review.carbonrom.org/#/c/407/

Thank you for your attention to this.
